sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.1
          env: DEPENDENCIES=lowest

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$DEPENDENCIES" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
    - make travis

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $HOME/.composer/cache
